window.invitados = {
  '1': { nombre: 'Lupita Marcia', pases: 2 },
  '2': { nombre: 'Valeria Castillo', pases: 1 },
  '3': { nombre: 'Andrea Noriega', pases: 1 },
  '4': { nombre: 'Esteban Ramirez', pases: 1 },
  '5': { nombre: 'Kristell Navas', pases: 1 },
  '6': { nombre: 'Doris Pinto', pases: 1 },
  '7': { nombre: 'Fernanda Olivares', pases: 1 },
  '8': { nombre: 'Roxana Montepeque', pases: 1 },
  '9': { nombre: 'Jorge Gómez', pases: 1 },
  '10': { nombre: 'Raul Hernandez', pases: 1 },
  '11': { nombre: 'Ashly Paz', pases: 1 },
  '12': { nombre: 'Linda Soto', pases: 1 },
  '13': { nombre: 'Andres Juarez', pases: 1 },
  '14': { nombre: 'Enrique Gómez', pases: 1 },
  '15': { nombre: 'Samuel Antuche', pases: 1 },
  '16': { nombre: 'Josué Paz', pases: 1 },
  '17': { nombre: 'Daniel Paz', pases: 1 },
  '18': { nombre: 'Emilio Gutierrez', pases: 1 },
  '19': { nombre: 'Dulce Barrientos', pases: 1 },
  '20': { nombre: 'Eliam Claudio', pases: 1 },
  '21': { nombre: 'Christopher Chavarría', pases: 1 },
  '22': { nombre: 'Familia De León Cruz', pases: 2 },
  '23': { nombre: 'Familia de León Arrillaga', pases: 4 },
  '24': { nombre: 'Familia De León Ramirez', pases: 4 },
  '25': { nombre: 'Familia Canel Guevara', pases: 3 },
  '26': { nombre: 'Carolina Canel', pases: 1 },
  '27': { nombre: 'Familia Martinez Canel', pases: 2 },
  '28': { nombre: 'Familia Canel Pereira', pases: 4 },
  '29': { nombre: 'Familia Guevara Pérez', pases: 2 },
  '30': { nombre: 'Eulalio Canel', pases: 1 },
  '31': { nombre: 'Maco Canel', pases: 1 },
  '32': { nombre: 'Familia López Ramos', pases: 4 },
  '33': { nombre: 'Familia Gamarra de León', pases: 4 },
  '34': { nombre: 'Familia Cruz Avalos', pases: 3 },
  '35': { nombre: 'Familia Villar De León', pases: 2 },
  '36': { nombre: 'Yadira De León', pases: 2 },
  '37': { nombre: 'Familia Mendez Gil', pases: 2 },
  '38': { nombre: 'Familia Cividaniz Mendez', pases: 5 },
  '39': { nombre: 'Familia Tol Mendez', pases: 5 },
  '40': { nombre: 'Familia Mendez Vargas', pases: 5 },
  '41': { nombre: 'Familia Herrera Méndez', pases: 5 },
  '42': { nombre: 'Mariana Acuña', pases: 4 },
  '43': { nombre: 'Familia López Zelada', pases: 5 },
  '44': { nombre: 'Betzaida De León', pases: 2 },
  '45': { nombre: 'Familia De León Urizar', pases: 2 },
  '46': { nombre: 'Familia De León Galindo', pases: 2 },
  '47': { nombre: 'Familia de León Lopez', pases: 2 },
  '48': { nombre: 'Mary Monzón', pases: 2 },
  '49': { nombre: 'Mary Caal', pases: 1 },
  '50': { nombre: 'Manuel Monje', pases: 2 },
  '51': { nombre: 'Erick Aldana', pases: 2 },
  '52': { nombre: 'Elizabeth Fajardo', pases: 2 },
  '53': { nombre: 'Familia Escobar Hernández', pases: 2 },
  '54': { nombre: 'Mario Tortola', pases: 1 },
  '55': { nombre: 'sin nombre', pases: 1 },
  '56': { nombre: 'sin nombre', pases: 2 },
  '57': { nombre: 'sin nombre', pases: 3 },
  '58': { nombre: 'sin nombre', pases: 4 },
  '59': { nombre: 'sin nombre', pases: 5 },
  '60': { nombre: 'Damaris Pineda', pases: 1 },
  '61': { nombre: 'José Merida', pases: 1 },
};

  